version: 2.1

npmrc: &npmrc
  run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

ignore-main-branch: &ignore-main-branch
  branches:
    ignore: main

only-main-branch: &only-main-branch
  branches:
    only: main

commands:
  yarn-install:
    description: Install cached yarn packages
    steps:
      - restore_cache:
          keys: ['v2-{{ checksum "yarn.lock" }}']
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn install --frozen-lockfile

  yarn-save-cache:
    description: Save yarn packages cache
    steps:
      - save_cache:
          key: v2-{{ checksum "yarn.lock" }}
          paths: ["~/.cache"]

jobs:
  test-and-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run:
          command: |
            yarn lint
            yarn test
      - run: yarn build
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - dist/

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - *npmrc
      - run: yarn build
      - run: git config user.email "tjworks@hotmail.co.uk
      - run: git config user.name "MrKiplin"
      - run: yarn publish

workflows:
  all-commits:
    jobs:
      - test-and-build:
          filters: *ignore-main-branch
      - publish:
          requires:
            - test-and-build
  master:
    jobs:
      - test-and-build:
          filters: *only-main-branch
      - publish:
          requires:
            - test-and-build
